runtime: python310
env: standard
entrypoint: gunicorn -b :$PORT msinventory.wsgi:application

runtime_config:
  python_version: 3.10

env_variables:
  DJANGO_SETTINGS_MODULE: 'msinventory.settings'
  SECRET_KEY: 'your-production-secret-key-change-this'
  DEBUG: 'False'

handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: auto

automatic_scaling:
  min_instances: 1
  max_instances: 2